export const pins = [
    {
        user: '@verovelazquez',
        title: 'Example1',
        src: 'assets/img/building/imagen1.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['building', 'window', 'white'],
        creationDate: new Date(),
    },
    {
        user: '@raulhuelamo',
        title: 'Example2',
        src: 'assets/img/lights/imagen1.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['lights', 'yellow', 'window', 'people', 'couple'],
        creationDate: new Date(),
    },
    {
        user: '@evaplaza',
        title: 'Example3',
        src: 'assets/img/people/imagen2.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['people', 'street', 'car'],
        creationDate: new Date(),
    },
    {
        user: '@saraalcantara',
        title: 'Example4',
        src: 'assets/img/imagen2.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['building', 'otro'],
        creationDate: new Date(),
    },
    {
        user: '@lauralara',
        title: 'Example5',
        src: 'assets/img/people/imagen3.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['people', 'otro'],
        creationDate: new Date(),
    },
    {
        user: '@carlosmasedo',
        title: 'Example6',
        src: 'assets/img/imagen4.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['lights', 'otro'],
        creationDate: new Date(),
    },
    {
        user: '@saraalcantara',
        title: 'Example6',
        src: 'assets/img/imagen3.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['car', 'porche'],
        creationDate: new Date(),
    },
    {
        user: '@evaplaza',
        title: 'Example6',
        src: 'assets/img/imagen6.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['sunset', 'city', 'San Francisco', 'bridge'],
        creationDate: new Date(),
    },
    {
        user: '@verovelazquez',
        title: 'Example6',
        src: 'assets/img/imagen7.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['lights', 'city', 'view', 'mountain'],
        creationDate: new Date(),
    },
    {
        user: '@raulhuelamo',
        title: 'Example6',
        src: 'assets/img/imagen8.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['people', 'travel', 'couple', 'photo'],
        creationDate: new Date(),
    },
    {
        user: '@lauralara',
        title: 'Example6',
        src: 'assets/img/imagen5.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['lights', 'car', 'sun', 'sunset'],
        creationDate: new Date(),
    },
    {
        user: '@tanianela',
        title: 'Example6',
        src: 'assets/img/imagen4.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['view', 'building', 'house', 'sea', 'sky', 'city'],
        creationDate: new Date(),
    },
    {
        user: '@tanianela',
        title: 'Example6',
        src: 'assets/img/imagen1.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['lights', 'plane', 'travel', 'window', 'sun'],
        creationDate: new Date(),
    },
    {
        user: '@anaanula',
        title: 'Example6',
        src: 'assets/img/imagen2.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['lights', 'car', 'street', 'porche', 'NY'],
        creationDate: new Date(),
    },
]

