export const pins = [
    {
        id: 0,
        user: '@verovelazquez',
        title: 'Example1',
        src: 'src/img/building/imagen1.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['building', 'otro', 'otro', 'otro'],
        creationDate: new Date(),
    },
    {
        id: 1,
        user: '@raulhuelamo',
        title: 'Example2',
        src: 'src/img/lights/imagen1.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['lights', 'otro', 'otro', 'otro'],
        creationDate: new Date(),
    },
    {
        id: 2,
        user: '@evaplaza',
        title: 'Example3',
        src: 'src/img/people/imagen2.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['people', 'otro', 'otro', 'otro'],
        creationDate: new Date(),
    },
    {
        id: 3,
        user: '@saraalcantara',
        title: 'Example4',
        src: 'src/img/building/imagen2.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['building', 'otro', 'otro', 'otro'],
        creationDate: new Date(),
    },
    {
        id: 4,
        user: '@lauralara',
        title: 'Example5',
        src: 'src/img/people/imagen3.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['people', 'otro', 'otro', 'otro'],
        creationDate: new Date(),
    },
    {
        id: 5,
        user: '@carlosmasedo',
        title: 'Example6',
        src: 'src/img/lights/imagen4.jpg',
        link: 'www.instagram.com/veris257',
        tags: ['lights', 'otro', 'otro', 'otro'],
        creationDate: new Date(),
    },
]
